package com.studyfi.contentandnews.chat.dto;

import lombok.Data;

import java.util.List;

@Data
public class PostLikesSummaryDTO {
    private Integer likeCount;
    private List<UserDTO> likedUsers;
    private boolean likedByCurrentUser;

    // Getters and Setters are automatically generated by Lombok's @Data annotation
}